import smtplib
import json
import os
import markdown
import sys
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

def send_email():
    """Reads email_config.json and sends the notification."""
    config_path = 'email_config.json'
    
    if not os.path.exists(config_path):
        print(f"[{config_path}] not found. Skipping email notification.")
        return

    try:
        with open(config_path, 'r') as f:
            config = json.load(f)
    except Exception as e:
        print(f"Error loading {config_path}: {e}")
        return

    recipient = config.get('recipient')
    if not recipient:
        print("No recipient specified in config. Skipping email.")
        return

    app_name = config.get('app_name', 'App')
    dashboard_url = config.get('dashboard_url', '#')
    body_md = config.get('body_md', '')
    
    sender_email = os.getenv("EMAIL_SENDER")
    sender_password = os.getenv("EMAIL_PASSWORD")

    if not sender_email or not sender_password:
        print("EMAIL_SENDER or EMAIL_PASSWORD not set. Skipping email.")
        return

    # Convert Markdown to HTML
    html_content = markdown.markdown(body_md)

    # Email Subject
    subject = f"Weekly Pulse: {app_name} Review Insights"

    # Construct HTML Body with Button
    email_body = f"""
    <html>
    <head>
        <style>
            body {{ font-family: 'Helvetica', 'Arial', sans-serif; line-height: 1.6; color: #333; }}
            .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
            .header {{ background-color: #f8fafc; padding: 20px; text-align: center; border-bottom: 1px solid #e2e8f0; }}
            .content {{ padding: 20px 0; }}
            .footer {{ text-align: center; font-size: 12px; color: #94a3b8; margin-top: 30px; }}
            .button {{
                display: block;
                width: 200px;
                margin: 30px auto;
                padding: 12px 24px;
                background-color: #4f46e5;
                color: #ffffff;
                text-decoration: none;
                border-radius: 8px;
                text-align: center;
                font-weight: bold;
            }}
            .button:visited {{ color: #ffffff; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h2>📊 App Review Analytics</h2>
            </div>
            <div class="content">
                {html_content}
                
                <a href="{dashboard_url}" class="button">Open Interactive Dashboard</a>
            </div>
            <div class="footer">
                <p>Generated by App Review Analytics AI • NextLeap Milestone 2</p>
            </div>
        </div>
    </body>
    </html>
    """

    try:
        msg = MIMEMultipart()
        msg['From'] = sender_email
        msg['To'] = recipient
        msg['Subject'] = subject
        msg.attach(MIMEText(email_body, 'html'))

        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, sender_password)
        text = msg.as_string()
        server.sendmail(sender_email, recipient, text)
        server.quit()
        print(f"✅ Notification email dispatched to {recipient}")
        
    except Exception as e:
        print(f"❌ Failed to send email: {e}")

if __name__ == "__main__":
    send_email()
